apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq
          ports:
            - containerPort: 5672
          env:
            - name: YES_SIR
              value: adsadsadsadas
          envFrom:
            - configMapRef:
              name: config-name

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
    - name: rabbitmq
      port: 5672
      protocol: TCP
      targetPort: 5672


apiVersion: v1
kind: ConfigMap
metadata:
  name: global-dtaasda
data:
  THE_STUFF: "asdas"
